/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.managesalonPalace;

import javax.swing.JOptionPane;

/**
 *
 * @author maceira_barca_xian
 */
public class ManageSalonPalaceJDialog extends javax.swing.JDialog {

    /**
     * Creates new form manageSalonPalaceJDialog
     */
    public ManageSalonPalaceJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eventTypeButtonGroup = new javax.swing.ButtonGroup();
        salonPalaceLabel = new javax.swing.JLabel();
        fullNameJLabel = new javax.swing.JLabel();
        fullNameTextField = new javax.swing.JTextField();
        eventInfoJLabel = new javax.swing.JLabel();
        emailJLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        phoneJLabel = new javax.swing.JLabel();
        phoneTextField = new javax.swing.JTextField();
        personalInfoLabel1 = new javax.swing.JLabel();
        separatorjLabel1 = new javax.swing.JLabel();
        datejLabel = new javax.swing.JLabel();
        datejTextField = new javax.swing.JTextField();
        attendancejLabel = new javax.swing.JLabel();
        attendanceSpinner = new javax.swing.JSpinner();
        cusineTypeComboBox = new javax.swing.JComboBox<>();
        cuisineTypejLabel = new javax.swing.JLabel();
        attendaceBedroomLabel = new javax.swing.JLabel();
        sendButton = new javax.swing.JButton();
        eventTypeLabel = new javax.swing.JLabel();
        feastRadioButton = new javax.swing.JRadioButton();
        meetingRadioButton = new javax.swing.JRadioButton();
        congressRadioButton = new javax.swing.JRadioButton();
        attendanceCheckBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 51, 51));

        salonPalaceLabel.setFont(new java.awt.Font("Meera", 1, 36)); // NOI18N
        salonPalaceLabel.setText("Salón Palace");

        fullNameJLabel.setText("Nombre Completo");

        fullNameTextField.setToolTipText("Full Name");
        fullNameTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fullNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullNameTextFieldActionPerformed(evt);
            }
        });

        eventInfoJLabel.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        eventInfoJLabel.setText("INFORMACIÓN DEL EVENTO");

        emailJLabel.setText("Correo Electronico");

        emailTextField.setToolTipText("EMail");
        emailTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        emailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldActionPerformed(evt);
            }
        });

        phoneJLabel.setText("Telefono");

        phoneTextField.setToolTipText("Phone");
        phoneTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        phoneTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneTextFieldActionPerformed(evt);
            }
        });

        personalInfoLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        personalInfoLabel1.setText("DATOS PERSONALES");

        separatorjLabel1.setText("----------------------------------------------------------------------------------------------------------");

        datejLabel.setText("Fecha (DD/MM/AAAA)");

        datejTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        datejTextField.setToolTipText("Date");
        datejTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        attendancejLabel.setText("Asistentes");

        attendanceSpinner.setToolTipText("Attendance");
        attendanceSpinner.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cusineTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sin servicio de cocina", "Buffet", "Carta", "Cita con el chef", " " }));
        cusineTypeComboBox.setToolTipText("Cuisinbe Style");
        cusineTypeComboBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cuisineTypejLabel.setText("Tipo de cocina");

        attendaceBedroomLabel.setText("Habitaciones para asistentes necesarias?");

        sendButton.setText("Enviar Solicitud");
        sendButton.setToolTipText("Send");
        sendButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });

        eventTypeLabel.setText("Tipo de evento:");

        eventTypeButtonGroup.add(feastRadioButton);
        feastRadioButton.setText("Banquete");
        feastRadioButton.setToolTipText("Feast");

        eventTypeButtonGroup.add(meetingRadioButton);
        meetingRadioButton.setText("Jornada");
        meetingRadioButton.setToolTipText("Meeting");

        eventTypeButtonGroup.add(congressRadioButton);
        congressRadioButton.setText("Congreso");
        congressRadioButton.setToolTipText("Congress");

        attendanceCheckBox.setText("Si");
        attendanceCheckBox.setToolTipText("Yes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(datejTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(datejLabel, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(71, 71, 71)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(attendancejLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(attendanceSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(attendaceBedroomLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(202, 202, 202)
                                .addComponent(sendButton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(attendanceCheckBox)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cusineTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(cuisineTypejLabel)
                                    .addGap(42, 42, 42)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eventInfoJLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(separatorjLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(eventTypeLabel)
                                .addGap(18, 18, 18)
                                .addComponent(feastRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(meetingRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(congressRadioButton))
                            .addComponent(personalInfoLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(salonPalaceLabel)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(fullNameJLabel)
                                            .addComponent(fullNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addComponent(emailJLabel)))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(phoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(phoneJLabel)
                                        .addGap(53, 53, 53)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(salonPalaceLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(emailJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(personalInfoLabel1)
                        .addGap(5, 5, 5)
                        .addComponent(fullNameJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fullNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(phoneJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(phoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addComponent(separatorjLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eventInfoJLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(feastRadioButton)
                    .addComponent(meetingRadioButton)
                    .addComponent(congressRadioButton)
                    .addComponent(eventTypeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datejLabel)
                    .addComponent(attendancejLabel)
                    .addComponent(cuisineTypejLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(attendanceSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cusineTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(attendaceBedroomLabel)
                    .addComponent(attendanceCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sendButton)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fullNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullNameTextFieldActionPerformed

    private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldActionPerformed

    private void phoneTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneTextFieldActionPerformed

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        int dialogResult = JOptionPane.showConfirmDialog(this, "¿Está seguro de enviar la solicitud?", "Confirmación", JOptionPane.YES_NO_OPTION);

        if (dialogResult == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(this, "Reserva realizada");
        } else {
            this.dispose();
        }

    }//GEN-LAST:event_sendButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageSalonPalaceJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageSalonPalaceJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageSalonPalaceJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageSalonPalaceJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ManageSalonPalaceJDialog dialog = new ManageSalonPalaceJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel attendaceBedroomLabel;
    private javax.swing.JCheckBox attendanceCheckBox;
    private javax.swing.JSpinner attendanceSpinner;
    private javax.swing.JLabel attendancejLabel;
    private javax.swing.JRadioButton congressRadioButton;
    private javax.swing.JLabel cuisineTypejLabel;
    private javax.swing.JComboBox<String> cusineTypeComboBox;
    private javax.swing.JLabel datejLabel;
    private javax.swing.JTextField datejTextField;
    private javax.swing.JLabel emailJLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel eventInfoJLabel;
    private javax.swing.ButtonGroup eventTypeButtonGroup;
    private javax.swing.JLabel eventTypeLabel;
    private javax.swing.JRadioButton feastRadioButton;
    private javax.swing.JLabel fullNameJLabel;
    private javax.swing.JTextField fullNameTextField;
    private javax.swing.JRadioButton meetingRadioButton;
    private javax.swing.JLabel personalInfoLabel1;
    private javax.swing.JLabel phoneJLabel;
    private javax.swing.JTextField phoneTextField;
    private javax.swing.JLabel salonPalaceLabel;
    private javax.swing.JButton sendButton;
    private javax.swing.JLabel separatorjLabel1;
    // End of variables declaration//GEN-END:variables
}
